spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: validate
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath*:db/db_changelog-master.yaml
  doc:
    swagger_ui:
      enabled: true
      version: 3.1.0
    api-docs:
      version: openapi.3.1

server:
  port: 8080

my:
  reportContainer: ${alias_report}
  port: ${port_report}