spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: validate
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath*:db/db_changelog-master.yaml
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8070

my:
  myminio: myminio
  port: 8091