version: '3.9'

services:
  postgresContainer:
    image: postgres:14.1
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: RvipLabs
    networks:
      backend:
        aliases:
          - "postgresContainer"

  applicationContainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: application
    container_name: app-container
    environment:
      db_url: jdbc:postgresql://postgresContainer:5432/RvipLabs
      db_user: postgres
      db_password: postgres
      alias_report: "reportContainer"
      port_report: "8070"
    ports:
      - "8080:8080"
    networks:
      backend:
        aliases:
          - "applicationContainer"

  reportContainer:
    image: report/report
    container_name: report-container
    environment:
      db_url: jdbc:postgresql://postgresContainer:5432/RvipLabs
      db_user: postgres
      db_password: postgres
#Это для 2 лабы
#    ports:
#      - "8070:8070"
#А это для 3 лабы
    ports:
      - "8070:8080"
    networks:
      backend:
        aliases:
          - "reportContainer"

  gateway:
    image: gateway/gateway
    ports:
      - "8072:8072"
    networks:
      backend:
        aliases:
          - "gateway"

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: provider
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-storage:/data
    networks:
      backend:
        aliases:
          - "minio"

  myminio:
    image: myminio/myminio
    ports:
      - "8091:8081"
    networks:
      backend:
        aliases:
          - "myminio"

networks:
  backend:
    driver: bridge

volumes:
  minio-storage: